### ISSUE TITLE
`default` choice not being respected

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-fancy-profiles#84]
With the following config:

```yaml
          image:
              display_name: Image
              unlisted_choice: &profile_list_unlisted_choice
                enabled: True
                display_name: "Custom image"
                validation_regex: "^.+:.+$"
                validation_message: "Must be a publicly available docker image, of form <image-name>:<tag>"
                kubespawner_override:
                  image: "{value}"
              choices:
                pangeo:
                  display_name: Base Pangeo Notebook (2024.10.26)
                  default: true
                  slug: "pangeo"
                  kubespawner_override:
                    image: "pangeo/pangeo-notebook:2024.10.26"
                tensorflow:
                  display_name: Pangeo Tensorflow ML Notebook (2024.10.26)
                  slug: "tensorflow"
                  kubespawner_override:
                    image: "pangeo/ml-notebook:2024.10.26"
                pytorch:
                  display_name: Pangeo PyTorch ML Notebook (2024.10.26)
                  slug: "pytorch"
                  kubespawner_override:
                    image: "pangeo/pytorch-notebook:2024.10.26"
                leap-pangeo-edu:
                  display_name: LEAP Education Notebook (Testing Prototype)
                  slug: "leap_edu"
                  kubespawner_override:
                    image: "quay.io/jbusecke/leap-edu-image:fa442ab4851c"
```

I see this as the default:

<img width="815" alt="image" src="https://github.com/user-attachments/assets/bc0374ce-0873-4023-912c-68e214955e73">

Note that the last item (`LEAP Education Notebook (Testing Prototype)`) is being selected as the default, rather than what has `default: true`.

https://github.com/2i2c-org/infrastructure/blob/ead78f7019ec333b6c73b4c9f5e1e20d5af7d506/config/clusters/leap/daskhub-common.values.yaml#L153 is the full config
